version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: cogtechai-mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: cogtechai
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend-api:
    build:
      context: ./backend-api
    container_name: cogtechai-backend
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  ai-service:
    build:
      context: ./ai-service
    container_name: cogtechai-ai-service
    ports:
      - "5001:8000"
    env_file:
      - ./ai-service/.env
    depends_on:
      - backend-api

  frontend:
    build:
      context: ./frontend
    container_name: cogtechai-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend-api

volumes:
  mysql-data:
