services:
  - type: web
    name: cogtechai-frontend
    env: docker
    plan: free
    repo: https://github.com/AbrahamBollarapu/cogtechai-mvp
    branch: main
    rootDir: frontend
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /

  - type: web
    name: cogtechai-backend
    env: docker
    plan: free
    repo: https://github.com/AbrahamBollarapu/cogtechai-mvp
    branch: main
    rootDir: backend-api
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /api/health

  - type: web
    name: cogtechai-ai-service
    env: docker
    plan: free
    repo: https://github.com/AbrahamBollarapu/cogtechai-mvp
    branch: main
    rootDir: ai-service
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /ai/generate

databases:
  - name: cogtechai-db
    plan: free
    postgresMajorVersion: 15
